config/routes.rb
Rails.application.routes.draw do
  devise_for :admins, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  get 'pages/index'
  resources :products, only: [:index, :show]
  resources :contacts, only: [:new,:create]

  root 'pages#under_construction'
end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, 
         :recoverable, :rememberable, :trackable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/contact.rb
class Contact < ApplicationRecord
end

app/models/product.rb
class Product < ApplicationRecord
  attr_accessor :images_raw
  before_create :set_images

  scope :pinneds, -> {where(pinned: true)}

  def images_raw
    self.images.join("\n") unless self.images.nil?
  end

  def images_raw=(values)
    self.images = []
    self.images=values.split("\n")
  end

  def set_images
    self.images=self.images_raw.split("\n") if self.images_raw
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
  def create
    @contact = Contact.new(contact_params)
    if @contact.save
      flash[:success] = "Se ha enviado el mensaje satisfactoriamente!"
    else
      flash[:error] = "Hubo un error! intente más tarde."
    end
    @contact = Contact.new
    respond_to do |format|
      format.js {render :show}
    end
  end

  private
    def contact_params
      params.permit(:name, :phone, :message, :email)
    end
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index
  	@title = "HomePage"
  	@products = Product.all
  	@contact = Contact.new
  	@page_scroll = true
  end

  def under_construction
  	@title = "En Construcción"
  	@disable_navigation = true
  end

end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
  def index
    @products = Product.all
    @page_scroll = false
    @current_path = "products"
    @enable_sidebar = true
    @title = "Productos"
    puts params[:controller]
  end
  def show
    @product = Product.find(params[:id])
    
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def flash_class(level)
    case level
      when "notice" then "alert alert-info"
      when "success" then "alert alert-success"
      when "error" then "alert alert-error"
      when "alert" then "alert alert-error"
      else "alert alert-info"
    end
  end
end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/contacts/_alert.html.erb
<% flash.each do |key, value| %>
  <div class="<%= flash_class(key) %> data-dismissible">
    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
    <%=value%>
  </div>
<% end -%>

app/views/contacts/show.js.erb
$("#response").html("<%= escape_javascript(render 'alert')%>");
$('#new_contact')[0].reset();

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Sumiledsa - <%=@title%></title>
    <%= csrf_meta_tags %>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Dixon Garcia">
    <%= stylesheet_link_tag    'application', media: 'all'%>
    

    <!-- Custom Fonts -->
    <link href="https://fonts.googleapis.com/css?family=Montserrat:400,700" rel="stylesheet" type="text/css">
    <link href='https://fonts.googleapis.com/css?family=Kaushan+Script' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Droid+Serif:400,700,400italic,700italic' rel='stylesheet' type='text/css'>
    <link href='https://fonts.googleapis.com/css?family=Roboto+Slab:400,100,300,700' rel='stylesheet' type='text/css'>

    <!-- favicon -->
    <link rel="apple-touch-icon" sizes="57x57" href="/apple-icon-57x57.png">
    <link rel="apple-touch-icon" sizes="60x60" href="/apple-icon-60x60.png">
    <link rel="apple-touch-icon" sizes="72x72" href="/apple-icon-72x72.png">
    <link rel="apple-touch-icon" sizes="76x76" href="/apple-icon-76x76.png">
    <link rel="apple-touch-icon" sizes="114x114" href="/apple-icon-114x114.png">
    <link rel="apple-touch-icon" sizes="120x120" href="/apple-icon-120x120.png">
    <link rel="apple-touch-icon" sizes="144x144" href="/apple-icon-144x144.png">
    <link rel="apple-touch-icon" sizes="152x152" href="/apple-icon-152x152.png">
    <link rel="apple-touch-icon" sizes="180x180" href="/apple-icon-180x180.png">
    <link rel="icon" type="image/png" sizes="192x192"  href="/android-icon-192x192.png">
    <link rel="icon" type="image/png" sizes="32x32" href="/favicon-32x32.png">
    <link rel="icon" type="image/png" sizes="96x96" href="/favicon-96x96.png">
    <link rel="icon" type="image/png" sizes="16x16" href="/favicon-16x16.png">
    <link rel="manifest" href="/manifest.json">
    <meta name="msapplication-TileColor" content="#ffffff">
    <meta name="msapplication-TileImage" content="/ms-icon-144x144.png">
    <meta name="theme-color" content="#ffffff">
  </head>

  <body id="page-top" class="index">
    <% unless @disable_navigation %>
      <!-- Navigation -->
      <nav id="mainNav" class="navbar navbar-default navbar-custom navbar-fixed-top">
          <div class="container">
              <!-- Brand and toggle get grouped for better mobile display -->
              <div class="navbar-header page-scroll">
                  <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1">
                      <span class="sr-only">Toggle navigation</span> Menu <i class="fa fa-bars"></i>
                  </button>
                  <a class="navbar-brand page-scroll" href="<%= '/' unless @page_scroll %>#page-top"><%= image_tag("logo.png")%></a>
              </div>

              <!-- Collect the nav links, forms, and other content for toggling -->
              <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
                  <ul class="nav navbar-nav navbar-right">
                      <li class="hidden">
                          <a href="<%= '/' unless @page_scroll %>#page-top"></a>
                      </li>
                      <li>
                          <a class="page-scroll" href="<%= '/' unless @page_scroll %>#services">Servicios</a>
                      </li>
                      <li>
                          <a class="page-scroll" href="<%= '/' unless @page_scroll %>#highlights">Destacados</a>
                      </li>
                      <li class="<%= @current_path == 'products' ? 'active' : 'no-active' %>">
                          <a href="<%=products_path%>">Productos</a>
                      </li>
                      <li>
                          <a class="page-scroll" href="<%= '/' unless @page_scroll %>#team">Team</a>
                      </li>
                      <li>
                          <a class="page-scroll" href="<%= '/' unless @page_scroll %>#contact">Contactanos</a>
                      </li>
                  </ul>
              </div>
              <!-- /.navbar-collapse -->
          </div>
          <!-- /.container-fluid -->
      </nav>
    <%end%>
    <%= yield %>
    <footer>
      <div class="container">
          <div class="row">
              <div class="col-md-4">
                  <span class="copyright">Copyright &copy; Sumiledsa <%= Date.today.year %></span>
              </div>
              <div class="col-md-4">
                  <ul class="list-inline social-buttons">
                      <li><a href="#"><i class="fab fa-facebook-f"></i></a>
                      </li>
                      <li><a href="https://www.instagram.com/sumiledsa/" target="blank"><i class="fab fa-instagram"></i></a>
                      </li>
                  </ul>
              </div>
              <div class="col-md-4">
                  <ul class="list-inline quicklinks">
                      <li><a href="#">Privacy Policy</a>
                      </li>
                      <li><a href="#">Terms of Use</a>
                      </li>
                  </ul>
              </div>
          </div>
      </div>
    </footer>
    <%= javascript_include_tag 'application'%>
    <% if controller_name == "products" %>
      <%= javascript_include_tag 'products' %>
    <%end%>
    <script type="text/javascript">
      <% if @page_scroll %>
        // Highlight the top nav as scrolling occurs
        $('body').scrollspy({
            target: '.navbar-fixed-top',
            offset: 51
        });
      <% end %>
    </script>
  </body>
</html>

app/views/pages/_modal.html.erb
<div class="portfolio-modal modal fade" id="<%= product.id %>" tabindex="-1" role="dialog" aria-hidden="true">
  <div class="modal-dialog">
    <div class="modal-content">
      <div class="close-modal" data-dismiss="modal">
        <div class="lr">
          <div class="rl"></div>
        </div>
      </div>
      <div class="container">
        <div class="row">
          <div class="col-lg-8 mx-auto">
            <div class="modal-body">
              <!-- Project Details Go Here -->
              <h2 class="text-uppercase">Project Name</h2>
              <p class="item-intro text-muted">Lorem ipsum dolor sit amet consectetur.</p>
              <img class="img-fluid d-block mx-auto" src="<%= product.images.first%>" alt="">
              <p>Use this area to describe your project. Lorem ipsum dolor sit amet, consectetur adipisicing elit. Est blanditiis dolorem culpa incidunt minus dignissimos deserunt repellat aperiam quasi sunt officia expedita beatae cupiditate, maiores repudiandae, nostrum, reiciendis facere nemo!</p>
              <ul class="list-inline">
                <li>Date: January 2017</li>
                <li>Client: Threads</li>
                <li>Category: Illustration</li>
              </ul>
              <button class="btn btn-primary" data-dismiss="modal" type="button">
                <i class="fa fa-times"></i>
                Close Project</button>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/pages/under_construction.html.erb
<!-- Header -->
<header class="construction">
    <div class="container">
        <div class="intro-text">
            <div class="intro-lead-in">Bienvenidos!</div>
            <div class="intro-heading">
            	<%= image_tag("logo.png", class: "img-responsive")%>
            </div>
            <div class="intro-lead-in">Estamos trabajando para ti!</div>
        </div>
    </div>
</header>

app/views/products/_sidebar.html.erb
<div id="sidebar" class="right sidebar fixed side-nav">
  <h4> Categorías </h4>
  <ul >
    <li><%= link_to 'Top level item', "#" , {class: "active"}%></li>
    <li>
      <input id="group-1" type="checkbox" hidden/>
      <label for="group-1"><span class="fa fa-angle-right"></span>First Level</label>
      <ul class="group-list">
        <li><%= link_to '1st level item', "#" %></li>
        <li>
          <input id="sub-group-1" type="checkbox" hidden />
          <label for="sub-group-1"><span class="fa fa-angle-right"></span> Second level</label>
          <ul class="sub-group-list">
            <li><%= link_to '2nd level item', "#" %></li>
            <li>
             <input id="sub-sub-group-1" type="checkbox" hidden />
              <label for="sub-sub-group-1"><span class="fa fa-angle-right"></span> Third level</label>
              <ul class="sub-sub-group-list">
                <li><%= link_to '3rd level item', "#" %></li>
              </ul>
            </li>
          </ul>
        </li>
      </ul>
    </li>
  </ul>
</div>

app/views/products/index.html.erb
<!-- Header -->
<header class="products">
  <div class="container">
    <div class="intro-text">
      <div class="intro-lead-in">SUMILED soluciones a tu medida</div>
      <div class="intro-heading">Productos y Servicios</div>
      <a href="#product" class="page-scroll btn btn-xl">Muestrame</a>
    </div>
  </div>
</header>
<%= render partial: "sidebar" %>
<div class="main">
  <section id="product">
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2 class="section-heading">Productos</h2>
          <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
        </div>      
      </div>
    </div>
    <div class="container">
      <div class="row">
        <% @products.each do |product| %>
          <div class="col-md-4 col-sm-6 portfolio-item">
            <a href="<%= product_path(product) %>" class="portfolio-link">
              <div class="portfolio-hover">
                <div class="portfolio-hover-content">
                  <i class="fas fa-plus fa-3x"></i>
                </div>
              </div>
              <img src="<%= product.images.first%>"class="img-responsive"/>
            </a>
            <div class="portfolio-caption">
              <h4><%=product.name%></h4>
              <!--<p class="text-muted">Graphic Design</p>-->
            </div>
          </div>
        <% end %>
      </div>
    <div class="container">
      <div class="row">
        <div class="col-lg-12 text-center">
          <h2 class="section-heading">Servicios</h2>
          <h3 class="section-subheading text-muted">Lorem ipsum dolor sit amet consectetur.</h3>
        </div>      
      </div>
    </div>
    <div class="container">
      <div class="row">
        <% @products.each do |product| %>
          <div class="col-md-4 col-sm-6 portfolio-item">
            <a href="<%= product_path(product) %>" class="portfolio-link">
              <div class="portfolio-hover">
                <div class="portfolio-hover-content">
                  <i class="fas fa-plus fa-3x"></i>
                </div>
              </div>
              <img src="<%= product.images.first%>"class="img-responsive"/>
            </a>
            <div class="portfolio-caption">
              <h4><%=product.name%></h4>
              <!--<p class="text-muted">Graphic Design</p>-->
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </section>
</div>

app/views/products/show.html.erb
<header class="product-detail">
  <div class="container">
    <div class="intro-text">
      <div class="intro-lead-in"></div>
      <div class="intro-heading"><%=@product.name%></div>
      <a href="#productImages" class="page-scroll btn btn-xl">Más</a>
    </div>
  </div>
</header>
<section id="details">
  <div id="productImages" class="carousel slide" data-ride="carousel">
    <!-- Indicators -->
    <ol class="carousel-indicators">
      <% (0..@product.images.size).each do |i| %>
        <li data-target="#productImages" data-slide-to="<%=i%>" class="<%= 'active' if i==0%>"></li>
      <%end%>
    </ol>

    <!-- Wrapper for slides -->
    <div class="carousel-inner">
      <% @product.images.each_with_index do |img,i| %>
        <div class="item <%= 'active' if i == 0%>">
          <img src="<%=img%>" >
        </div>
      <% end %>
    </div>

    <!-- Left and right controls -->
    <a class="left carousel-control" href="#productImages" data-slide="prev">
      <span class="glyphicon glyphicon-chevron-left"></span>
      <span class="sr-only">Previous</span>
    </a>
    <a class="right carousel-control" href="#productImages" data-slide="next">
      <span class="glyphicon glyphicon-chevron-right"></span>
      <span class="sr-only">Next</span>
    </a>
  </div>
</section>